/* Egg Timer: the hatchlings' puppet pieces (E45). GENERATED by make-alien-art.py: don't edit by hand.
   Each part's [width, height] in the nest's viewBox units; its picture is files/art/hatch-<alien>--<part>@2x.png. */
(function (root) {
  var ET = (root.ET = root.ET || {});
  ET.ALIEN_PARTS = {
    crab: { "body": [46.62, 42.25], "stalk-1": [22.62, 16.12], "stalk-2": [18.12, 19.25], "stalk-3": [11.5, 20.25], "leg-1": [29.0, 24.25], "leg-2": [15.5, 20.62], "leg-3": [34.38, 23.12], "leg-4": [24.0, 27.38] },
    scuttler: { "body": [34.75, 48.88], "leg": [38.0, 40.25], "mandible-l": [13.12, 16.62], "mandible-r": [13.25, 16.62] },
    worm: { "head": [24.12, 28.25], "segment": [23.38, 21.75], "tail": [22.38, 20.88], "antenna": [13.25, 26.12] },
    wriggler: { "body": [39.38, 57.25], "insides": [18.88, 31.25], "feeler-1": [21.5, 5.75], "feeler-2": [21.5, 5.75], "feeler-3": [21.62, 5.75], "feeler-4": [21.0, 5.25], "feeler-5": [17.75, 4.38], "feeler-6": [20.75, 5.62], "feeler-7": [16.75, 5.0], "feeler-8": [21.0, 4.75], "feeler-9": [17.38, 7.38], "feeler-10": [21.0, 5.38] },
    octopus: { "body": [61.12, 59.0], "tentacle-1": [30.12, 8.0], "tentacle-2": [30.12, 8.0], "tentacle-3": [30.38, 8.0], "tentacle-4": [29.38, 6.62] },
    grabber: { "body": [44.62, 56.25], "tentacle-1": [29.12, 7.88], "tentacle-2": [29.38, 7.25], "tentacle-3": [23.38, 6.88], "tentacle-4": [29.38, 7.5], "drip-1": [5.62, 10.12], "drip-2": [2.88, 6.38], "drip-3": [3.0, 11.75], "drip-4": [2.62, 7.75] }
  };
})(window);
