/* ============================================================================
 * PITSTOP — bake-data.mjs
 * ----------------------------------------------------------------------------
 * Inlines the dataset CSVs into files/datasets/embedded.js so the cartridge runs
 * by DOUBLE-CLICKING index.html (file://), where fetch() of local files is
 * blocked by the browser and cannot be worked around.
 *
 * RUN AFTER ANY CSV EDIT:   node bake-data.mjs
 *
 * The CSVs remain the source of truth (Laws §0.10). This script copies their
 * TEXT verbatim — it does no parsing, so it cannot alter or retype the data. The
 * engine parses the inlined strings with the same parsers it used for the
 * fetched files.
 * ========================================================================= */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = dirname(fileURLToPath(import.meta.url));
const DATASETS = join(ROOT, 'files', 'datasets');

// Keyed by the path the engine used to fetch — the loaders look up by this key.
const SOURCES = [
  'datasets/courses.csv',
  'datasets/coursestops.csv',
  'datasets/baselatlon.csv'
];

const baked = {};
for (const key of SOURCES) {
  const file = join(DATASETS, key.replace('datasets/', ''));
  // Strip BOM and normalise to LF so the generated file is stable in git
  // (.gitattributes pins the CSVs to LF). Parsers are CRLF-safe either way.
  const text = readFileSync(file, 'utf8').replace(/^﻿/, '').replace(/\r\n/g, '\n');
  baked[key] = text;
  const rows = text.split('\n').filter(l => l.trim()).length - 1;
  console.log(`  ${key.padEnd(26)} ${String(rows).padStart(3)} data rows`);
}

const stamp = new Date().toISOString().replace(/\.\d+Z$/, 'Z');
const body = SOURCES.map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(baked[k])}`).join(',\n');

const out = `/* ============================================================================
 * AUTO-GENERATED by bake-data.mjs — DO NOT EDIT BY HAND.
 * Baked: ${stamp}
 *
 * Verbatim copies of files/datasets/*.csv, inlined so the cartridge runs from
 * file:// (double-clicked index.html), where fetch() of local files is blocked.
 * The CSVs are still the source of truth — edit them, then re-bake:
 *
 *     node bake-data.mjs
 *
 * Edits made HERE are silently lost on the next bake.
 * ========================================================================= */

window.PITSTOP_CSV = {
${body}
};
window.PITSTOP_CSV_BAKED = ${JSON.stringify(stamp)};
`;

writeFileSync(join(DATASETS, 'embedded.js'), out);
console.log(`\nBaked ${SOURCES.length} datasets -> files/datasets/embedded.js (${stamp})`);
